version: 2
jobs:
  check:
    docker:
      - image: rust
    steps:
      - checkout
      - run: cargo check
  build:
    docker:
      - image: rust
    steps:
      - checkout
      - run: cargo build
  fmt:
    docker:
      - image: rust
    steps:
      - checkout
      - run: rustup component add rustfmt
      - run: cargo fmt
  lint:
    docker:
      - image: rust
    steps:
      - checkout
      - run: rustup component add clippy
      - run: cargo clippy
  test:
    docker:
      - image: rust
    steps:
      - checkout
      - run: cargo test

workflows:
  version: 2
  build_and_test:
    jobs:
      - check
      - build
      - fmt
      - lint
      - test
