version: 2
jobs:
  check:
    docker:
      - image: rust
    steps:
      - checkout
      - run: cargo check
      - save_cache:
          key: cargo-lock-{{ .BuildNum }}
          paths:
            - Cargo.lock
            - target
  build:
    docker:
      - image: rust
    steps:
      - checkout
      - restore_cache:
          key: cargo-lock-{{ .BuildNum }}
      - run: cargo build
  fmt:
    docker:
      - image: rust
    steps:
      - checkout
      - restore_cache:
          key: cargo-lock-{{ .BuildNum }}
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check
  lint:
    docker:
      - image: rust
    steps:
      - checkout
      - restore_cache:
          key: cargo-lock-{{ .BuildNum }}
      - run: rustup component add clippy
      - run: cargo clippy
  test:
    docker:
      - image: rust
    steps:
      - checkout
      - restore_cache:
          key: cargo-lock-{{ .BuildNum }}
      - run: cargo test
  deploy:
    docker:
      - image: rust
    steps:
      - checkout
      - restore_cache:
          key: cargo-lock-{{ .BuildNum }}
      - run: cargo login $REGISTRY_LOGIN_API_TOKEN
      - run: cargo package
      - run: cargo publish

workflows:
  version: 2
  build_and_test:
    jobs:
      - check:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - check
          filters:
            tags:
              only: /.*/
      - fmt:
          requires:
            - check
          filters:
            tags:
              only: /.*/
      - lint:
          requires:
            - check
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - check
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
            - fmt
            - lint
            - test
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}$/
            branches:
              ignore: /.*/
