version: 2
jobs:
  entrance:
    docker:
      - image: rust
    steps:
      - checkout
      - run: rustup component add clippy rustfmt
      - run: cargo fmt -- --check
      - run: cargo clippy -- -D wranings
      - run: cargo test
  deploy_entrance:
    docker:
      - image: rust
    steps:
      - checkout
      - run: cargo login $REGISTRY_LOGIN_API_TOKEN
      - run: cargo package
      - run: cargo publish

  derive_entrance:
    docker:
      - image: rust
    steps:
      - checkout
      - run: rustup component add clippy rustfmt
      - run:
          command: cargo fmt -- --check
          working_directory: entrance_derive
      - run:
          command: cargo clippy -- -D wranings
          working_directory: entrance_derive
      - run:
          command: cargo test
          working_directory: entrance_derive
  deploy_derive_entrance:
    docker:
      - image: rust
    steps:
      - checkout
      - run:
          command: cargo login $REGISTRY_LOGIN_API_TOKEN
          working_directory: entrance_derive
      - run:
          command: cargo package
          working_directory: entrance_derive
      - run:
          command: cargo publish
          working_directory: entrance_derive

workflows:
  version: 2
  build_and_test:
    jobs:
      - entrance:
          filters:
            tags:
              only: /.*/
      - derive_entrance:
          filters:
            tags:
              only: /.*/
      - deploy_entrance:
          requires:
            - entrance
            - deploy_derive_entrance
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}$/
            branches:
              ignore: /.*/
      - deploy_derive_entrance:
          requires:
            - derive_entrance
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}$/
            branches:
              ignore: /.*/
