version: 2
jobs:
  check:
    docker:
      - image: rust
    steps:
      - checkout
      - run: cargo check
  build:
    docker:
      - image: rust
    steps:
      - checkout
      - run: cargo build
  fmt:
    docker:
      - image: rust
    steps:
      - checkout
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check
  lint:
    docker:
      - image: rust
    steps:
      - checkout
      - run: rustup component add clippy
      - run: cargo clippy
  test:
    docker:
      - image: rust
    steps:
      - checkout
      - run: cargo test
  deploy:
    docker:
      - image: rust
    steps:
      - checkout
      - run: cargo login $REGISTRY_LOGIN_API_TOKEN
      - run: cargo package
      - run: cargo publish

workflows:
  version: 2
  build_and_test:
    jobs:
      - check
      - build:
          requires:
            - check
      - fmt:
          requires:
            - check
      - lint:
          requires:
            - check
      - test:
          requires:
            - check
