version: 2
jobs:
  check:
    docker:
      - image: rust
    steps:
      - checkout
      - run: cargo check
      - save_cache:
          key: cargo-lock-{{ .Revision }}
          paths:
            - Cargo.lock
            - target
  check-derive:
    docker:
      - image: rust
    steps:
      - checkout
      - run:
          command: cargo check
          working_directory: entrance_derive
      - save_cache:
          key: derive-cargo-lock-{{ .Revision }}
          paths:
            - entrance_derive/Cargo.lock
            - entrance_derive/target
  build:
    docker:
      - image: rust
    steps:
      - checkout
      - restore_cache:
          key: cargo-lock-{{ .Revision }}
      - run: cargo build
  build-derive:
    docker:
      - image: rust
    steps:
      - checkout
      - restore_cache:
          key: derive-cargo-lock-{{ .Revision }}
      - run:
          command: cargo build
          working_directory: entrance_derive
  fmt:
    docker:
      - image: rust
    steps:
      - checkout
      - restore_cache:
          key: cargo-lock-{{ .Revision }}
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check
  fmt-derive:
    docker:
      - image: rust
    steps:
      - checkout
      - restore_cache:
          key: derive-cargo-lock-{{ .Revision }}
      - run: rustup component add rustfmt
      - run:
          command: cargo fmt -- --check
          working_directory: entrance_derive
  lint:
    docker:
      - image: rust
    steps:
      - checkout
      - restore_cache:
          key: cargo-lock-{{ .Revision }}
      - run: rustup component add clippy
      - run: cargo clippy
  lint-derive:
    docker:
      - image: rust
    steps:
      - checkout
      - restore_cache:
          key: derive-cargo-lock-{{ .Revision }}
      - run: rustup component add clippy
      - run:
          command: cargo clippy
          working_directory: entrance_derive
  test:
    docker:
      - image: rust
    steps:
      - checkout
      - restore_cache:
          key: cargo-lock-{{ .Revision }}
      - run: cargo test
  test-derive:
    docker:
      - image: rust
    steps:
      - checkout
      - restore_cache:
          key: derive-cargo-lock-{{ .Revision }}
      - run:
          command: cargo test
          working_directory: entrance_derive
  deploy:
    docker:
      - image: rust
    steps:
      - checkout
      - restore_cache:
          key: cargo-lock-{{ .Revision }}
      - run: cargo login $REGISTRY_LOGIN_API_TOKEN
      - run: cargo package
      - run: cargo publish
  deploy-derive:
    docker:
      - image: rust
    steps:
      - checkout
      - restore_cache:
          key: derive-cargo-lock-{{ .Revision }}
      - run:
          command: cargo login $REGISTRY_LOGIN_API_TOKEN
          working_directory: entrance_derive
      - run:
          command: cargo package
          working_directory: entrance_derive
      - run:
          command: cargo publish
          working_directory: entrance_derive

workflows:
  version: 2
  build_and_test:
    jobs:
      - check:
          filters:
            tags:
              only: /.*/
      - check-derive:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - check
          filters:
            tags:
              only: /.*/
      - build-derive:
          requires:
            - check-derive
          filters:
            tags:
              only: /.*/
      - fmt:
          requires:
            - check
          filters:
            tags:
              only: /.*/
      - fmt-derive:
          requires:
            - check-derive
          filters:
            tags:
              only: /.*/
      - lint:
          requires:
            - check
          filters:
            tags:
              only: /.*/
      - lint-derive:
          requires:
            - check-derive
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - check
          filters:
            tags:
              only: /.*/
      - test-derive:
          requires:
            - check-derive
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
            - fmt
            - lint
            - test
            - deploy-derive
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}$/
            branches:
              ignore: /.*/
      - deploy-derive:
          requires:
            - build-derive
            - fmt-derive
            - lint-derive
            - test-derive
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}$/
            branches:
              ignore: /.*/
